### ISSUE TITLE
Run validator requires missing file

### ISSUE THREAD

**Issue by isoboroff** [irlabamsterdam/iKAT#2]
The run validator README says that you need a file `ikat_2023_passage_hashes.tsv`, but this file isn't in the repository or on the data page, that I can find.  (I'm sorry if I'm missing something obvious.)

**Comment by andrewramsay** [comment]
This file was originally one of the set that required team login credentials to download. However since this file only contains hashes there's now a public download link for it [here](https://ikattrecweb.grill.science/ikat_2023_passages_hashes.tsv.bz2) you should be able to use. 

(there was also a typo in the filename in the README, it should have been `ikat_2023_passages_hashes.tsv`)

**Comment by isoboroff** [comment]
Ah!  Thank you.
